name: trustlens
description: TrustLens - AI-powered content credibility analysis via Share Sheet
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  share_plus: ^10.0.0
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.2
  share_handler: ^0.0.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
